### ISSUE TITLE
Log Watcher Log file path is not configured!	

### ISSUE THREAD

**Issue by sanderkwantes** [magento-hackathon/Hackathon_MageMonitoring#29] opened 2015-02-10 16:18 UTC
I can't find anywhere were to fill in the log path, maybe i missed something, but i now receive messages with the following subject: MageMonitoring Watch Dog Reports from:  ! and with the following content: 
Log Watcher
Log file path is not configured!	

Can someone point me in the right direction?

**Comment by edannenberg** [comment] 2015-02-10 18:50
Widget config is usually done via the small gear icon in the widget title bar. Did you add a custom log widget or is this with the default config? If the widget display works fine (i.e. logs are shown) this might be a scope issue with the config and cron processing.

**Comment by ftbastler** [comment] 2015-02-28 20:32
Please help! I get these spam error emails a lot.

**Comment by ftbastler** [comment] 2015-03-11 15:28
Anything?

**Comment by Schrank** [comment] 2015-03-11 16:00
I think you have two options here:
1. you fix it yourself (PR is welcome)
2. you pay some one to fix it

I think searching for "Log file path is not configured" in the source code might help you.

**Comment by edannenberg** [comment] 2015-03-11 18:41
I'm rather short on time yea, would be helpful though if people could actually provide some details like i asked in my first reply. ;)

**Comment by Schrank** [comment] 2015-03-12 18:26
I did it:
> I think searching for "Log file path is not configured" in the source code might help you.

**Comment by edannenberg** [comment] 2015-03-12 18:57
Wasn't directed at you Fabian. The point I was trying to make was that if bug reporters take a little time to answer some straight questions, which would help me locate the issue quicker, I would be much more inclined to have a look.

**Comment by Schrank** [comment] 2015-03-12 23:04
The problem is, no one is interested to fix this bug. The project is closed and everyone is invited to open it again. That is the sad reality.

**Comment by diglin** [comment] 2015-03-12 23:05
What do you mean by the "Project is closed" ?

**Comment by diglin** [comment] 2015-03-12 23:14
@ftbastler just please provide more information about your problem: scenario & screenshots. Thanks in advance

**Comment by bfeser** [comment] 2015-04-23 07:01
File /app/code/community/Hackathon/MageMonitoring/Model/Widget/Log/Tail.php

in the Line 31 to 72 you find the config.

It worked for me.

Best regards
bfeser

**Comment by winkelsdorf** [comment] 2015-04-25 19:01
What a bad Issue (Bug) Report :(

@edannenberg: Same happened here when testing this Repo, too. Was using the Out-of-the-Box configuration, not adjusted anything. Looks like there's a missing check for a value being set.. Probably best to set a default path.

**Comment by edannenberg** [comment] 2015-04-27 15:59
Ok, thanks. Gonna take a look this week.

**Comment by winkelsdorf** [comment] 2015-04-27 17:54
Thank you! Let me know if there's anything I should test after you commited a fix.

**Comment by borriglione** [comment] 2015-04-29 07:37
I got the same error on my shops.

Parmeters / Environment to reproduce:
- CE 1.5-CE1.9
- Cronjobs active
- Extension installed freshly
- Backend config: System -> Configuration -> Advanced -> System not saved after extension installation

Debug output in
 Hackathon_MageMonitoring_Model_Widget_Log_Tail::initConfig(), Line 72 of $this->_config

```
2015-04-29T07:31:53+00:00 DEBUG (7): Array
(
    [0] => Array
        (
            [label] => Widget Configuration
        )

    [title] => Array
        (
            [scope] => widget
            [label] => Widget Title:
            [value] => Log Watcher
            [type] => text
            [required] => 1
            [tooltip] => 
        )

    [collapsed] => Array
        (
            [scope] => widget
            [label] => Do not render widget on pageload?
            [value] => 
            [type] => checkbox
            [required] => 
            [tooltip] => 
        )

    [display_prio] => Array
        (
            [scope] => widget
            [label] => Display priority (0=top):
            [value] => 20
            [type] => text
            [required] => 
            [tooltip] => 
        )

    [1] => Array
        (
            [label] => Watch Dog Settings
        )

    [cron/enabled] => Array
        (
            [scope] => global
            [label] => Dog is on duty:
            [value] => 1
            [type] => checkbox
            [required] => 
            [tooltip] => 
        )

    [cron/schedule] => Array
        (
            [scope] => global
            [label] => Schedule:
            [value] => */5 * * * *
            [type] => text
            [required] => 
            [tooltip] => 
        )

    [cron/barkon] => Array
        (
            [scope] => global
            [label] => Minimum bark level (warning|error):
            [value] => warning
            [type] => text
            [required] => 
            [tooltip] => 
        )

    [cron/mail_to] => Array
        (
            [scope] => global
            [label] => Barks at:
            [value] => general
            [type] => text
            [required] => 
            [tooltip] => Magento mail id (general, sales, etc) or valid email address.
        )

    [2] => Array
        (
            [label] => Log Settings
        )

    [linecount] => Array
        (
            [scope] => global
            [label] => Max. number of lines to tail:
            [value] => 60
            [type] => text
            [required] => 
            [tooltip] => 
        )

    [file_path] => Array
        (
            [scope] => widget
            [label] => Log file path:
            [value] => 
            [type] => text
            [required] => 1
            [tooltip] => Complete system path or relative from magento root or var/log.
        )

    [color] => Array
        (
            [scope] => widget
            [label] => Background color:
            [value] => info
            [type] => text
            [required] => 
            [tooltip] => success | info | warning | error
        )

)
```
Mail is triggered because Hackathon_MageMonitoring_Model_Widget_Log_Tail::watch() $logName is empty

**Comment by edannenberg** [comment] 2015-04-29 18:02
Had a quick look, issue is reproducible and apparently a regression related to https://github.com/magento-hackathon/Hackathon_MageMonitoring/commit/eb585448a40f5da216f5573eeefdbfa6dbabd9d7

Fix will follow shortly.

@borriglione Interesting, saving System -> Configuration -> Advanced -> System shouldn't really affect anything for this particular bug. Wasn't able to reproduce the described behavior either.

**Comment by edannenberg** [comment] 2015-04-29 19:34
Fix is up in [dev](https://github.com/magento-hackathon/Hackathon_MageMonitoring/tree/dev) branch, also fixed a couple of other minor issues along the way.

**Comment by winkelsdorf** [comment] 2015-04-29 20:01
Thank you! Will report back if there are still problems, target machine is out of reach for a week.

**Comment by puravida69at** [comment] 2015-05-08 22:30
I still got this failure email: Log file path not set. 

Dont know if it this  is helping (Test Report mail):

Class: Hackathon_MageMonitoring_Model_WatchDog_Error
Message: Watch dog runtime error reporting test.
Trace: #0 /var/www/vhosts/stoffschwester.at/httpdocs/app/code/community/Hackathon/MageMonitoring/Model/WatchDog/UberDog.php(63): Hackathon_MageMonitoring_Model_WatchDog_Error->watch() #1 /var/www/vhosts/stoffschwester.at/httpdocs/app/code/community/Hackathon/MageMonitoring/Model/Widget/System/Watchdog.php(75): Hackathon_MageMonitoring_Model_WatchDog_UberDog->triggerActiveDogs(false) #2 /var/www/vhosts/stoffschwester.at/httpdocs/app/code/community/Hackathon/MageMonitoring/controllers/Adminhtml/WidgetAjaxController.php(150): Hackathon_MageMonitoring_Model_Widget_System_Watchdog->testCallback() #3 /var/www/vhosts/stoffschwester.at/httpdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Hackathon_MageMonitoring_Adminhtml_WidgetAjaxController->execCallbackAction() #4 /var/www/vhosts/stoffschwester.at/httpdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('execCallback') #5 /var/www/vhosts/stoffschwester.at/httpdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http)) #6 /var/www/vhosts/stoffschwester.at/httpdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch() #7 /var/www/vhosts/stoffschwester.at/httpdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array) #8 /var/www/vhosts/stoffschwester.at/httpdocs/index.php(87): Mage::run('', 'store') #9 {main}

**Comment by diglin** [comment] 2015-05-09 09:35
@edannenberg please let me know the status on your side ? I saw that you have a "dev" branch, is it stable can we merge it in develop branch?

**Comment by edannenberg** [comment] 2015-05-09 12:16
@puravida69at I'm guessing you used master instead of dev branch? The fix isn't merged into master yet.

@diglin Should be fine for merging.

**Comment by diglin** [comment] 2015-05-09 12:37
@puravida69at a new version is on the way, you can use the develop branch if you wish. Be aware that we will move the repository to Firegento normally this week end

**Closed** 2015-05-09 12:41 UTC
Labels: bug
